---

- name: Disable Windows Automatic updates
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword
    state: present

- name: Cleanup WinSxS
  win_shell: Dism.exe /Online /Cleanup-Image /StartComponentCleanup

- name: Cleanup Service Pack
  win_shell: Dism.exe /Online /Cleanup-Image /SPSuperseded

- name: Disable hibernation
  win_shell: powercfg.exe /hibernate off

- name: Stop Windows update
  win_service:
    name: wuauserv
    state: stopped

- name: Remove temp files
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - C:\Windows\SoftwareDistribution\Download
    - C:\Temp
    - C:\Windows\Temp
    - C:\Users\vagrant\AppData\Local\Temp

- name: Remove all page files
  win_pagefile:
    remove_all: yes
    automatic: no
  register: _pagefile

- name: Reboot if page file changed
  win_reboot:
  when: _pagefile is changed

- name: Remove page file from C
  win_pagefile:
    drive: C
    state: absent

- name: Reboot if page file changed
  win_reboot:
  when: _pagefile is changed

- name: Defrag drive
  win_shell: 'defrag.exe C:'

- name: Download SDelete
  win_get_url:
    url: https://download.sysinternals.com/files/SDelete.zip
    dest: C:\SDelete.zip

- name: Extract SDelete
  win_unzip:
    src: C:\SDelete.zip
    dest: C:\SDelete
    delete_archive: yes

- name: Zero out free space
  win_shell: 'C:\SDelete\sdelete.exe -accepteula -q -z c:'
